Web/Areas/Admin/Controllers/BooksController.cs
using Common;
using Common.Enums;
using Data.Repositories;
using Entities;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Microsoft.EntityFrameworkCore;
using Services;
using Services.Dto;
using Services.Services.Utilities;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using WebFramework.Filters;

namespace Web.Areas.Admin.Controllers
{
    [Route("[area]/[controller]/[action]")]
    [Area("Admin")]
    [Controller]
    [ShowErrorPageType]
    public class BooksController : Controller
    {
        private readonly IBookService _bookService;
        private readonly IImageService _imageService;
        private readonly IRepository<BookList> _repository;
        private readonly IRepository<Book> _bRepository;

        public BooksController(IBookService bookService, IImageService imageService, IRepository<BookList> repository, IRepository<Book> bRepository)
        {
            _bookService = bookService;
            _imageService = imageService;
            _repository = repository;
            _bRepository = bRepository;
        }
        [HttpGet]
        public async Task<IActionResult> Index(CancellationToken cancellationToken)
        {
            var models = await _bookService.GetAllBookAsync(cancellationToken);
            return View(models);
        }

        [HttpGet]
        public ActionResult Create()
        {
            ViewBag.ViewTitle = "فرم افزودن کتاب";
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create([FromHeader]CancellationToken cancellationToken, BookDto bookDto, string imagename)
        {
            if (ModelState.IsValid)
            {
                bookDto.ImageUrl = imagename;
                var exists = await _bookService.BookExists(bookDto, cancellationToken);
                if (exists == true)
                {
                    TempData["Error"] = "این کتاب قبلا ثبت شده است";
                    return View(bookDto);
                }

                var res = await _bookService.AddBookAsync(bookDto, cancellationToken);
                TempData["Success"] = "تبریک . کتاب با موفقیت ثبت شد";
                return RedirectToAction(nameof(Index));
            }
            return View(bookDto);
        }

        public async Task<IActionResult> UploadImage(IEnumerable<IFormFile> files)
        {
            var filename = await _imageService.UploadFile(files, @"upload\image\book\");

            return Json(new { status = "success", message = "تصویر با موفقیت آپلود شد.", imagename = filename });
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int gbookid, [FromHeader] CancellationToken cancellationToken)
        {
            var res = await _bookService.DeleteAsync(gbookid, cancellationToken);
            if (res == true)
            {
                TempData["War"] = "کتاب مورد نظر حذف شد";
                return RedirectToAction(nameof(Index));
            }
            TempData["Error"] = "کتاب مورد نظر یافت نشد";
            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id, [FromHeader]CancellationToken cancellationToken)
        {
            ViewBag.ViewTitle = "فرم ویرایش کتاب";
            var model = await _bookService.FindBookById4EditAsync(id, cancellationToken);
            if (model == null)
            {
                TempData["Error"] = "این کتاب در سیستم وجود ندارد";
                return RedirectToAction(nameof(Index));
            }

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Edit([FromHeader]CancellationToken cancellationToken, BookDto bookDto, string imagename)
        {
            foreach (var modelState in ViewData.ModelState.Values)
            {
                foreach (ModelError error in modelState.Errors)
                {
                    TempData["Error"] = error.ErrorMessage;
                }
            }
            if (ModelState.IsValid)
            {
                if (imagename != null)
                    bookDto.ImageUrl = imagename;
                var exists = await _bookService.EditAsync(bookDto, cancellationToken);

                if (exists != true)
                {
                    TempData["Error"] = "این کتاب در سیستم وجود ندارد";
                    return RedirectToAction(nameof(Index));
                }

                TempData["Success"] = "تبریک . ویرایش با موفقیت انجام شد";
                return RedirectToAction(nameof(Index));
            }
            return View(bookDto);
        }


        [HttpGet("id:int")]
        public async Task<IActionResult> DeleteOneBook([FromHeader]CancellationToken cancellationToken, int id)
        {
            var exists = await _repository.Table.Where(c => c.Id == id).Include(c => c.Books).FirstOrDefaultAsync(cancellationToken);

            if (exists == null)
            {
                TempData["Error"] = "این کتاب در سیستم وجود ندارد";
                return RedirectToAction(nameof(Index));
            }
            var bookCount = exists.Books.Count;
            if (bookCount > 1)
            {
                var deletBook = await _bRepository.Table.FirstOrDefaultAsync(c => c.BookListId == id, cancellationToken);
                await _bRepository.DeleteAsync(deletBook, cancellationToken);
            }
            else
            {
                try
                {
                    var deletBook = await _bRepository.Table.FirstOrDefaultAsync(c => c.BookListId == id, cancellationToken);
                    await _bRepository.DeleteAsync(deletBook, cancellationToken);
                    await _bookService.DeleteAsync(exists.Id, cancellationToken);
                }
                catch (System.Exception)
                {

                    throw;
                }
            }
            TempData["Success"] = "کتاب با موفقیت حذف شد";
            return RedirectToAction(nameof(Index));

        }

        [HttpGet("id:int")]
        public async Task<IActionResult> Details(int id, [FromHeader]CancellationToken cancellationToken)
        {
            var model = await _bookService.FindBookByIdAsync(id, cancellationToken);
            return View(model);
        }

    
        public async Task<IActionResult> Search(CancellationToken cancellationToken, Language lan, CourseType ctype, int field, BookStatus bstatus, Pagable pagable)
        {
            var model = await _bookService.GetAllBookAsync(cancellationToken, ctype, bstatus, lan, field, pagable.Search);
            //return Ok(model);
            return View(nameof(Index),model);
        }
    }
}

Web/Areas/Admin/Controllers/SettingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Entities;
using Microsoft.AspNetCore.Mvc;
using Services;

namespace Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Route("Admin/Setting/[action]")]
    public class SettingController : Controller
    {
        private readonly ISettingService _settingService;

        public SettingController(ISettingService settingService)
        {
            _settingService = settingService;
        }

        public async Task<IActionResult> Index(CancellationToken cancellationToken)
        {
            var model = await _settingService.GetAsync(cancellationToken);
            return View(model);

        }

        [HttpGet]
        public async Task<IActionResult> Edit(CancellationToken cancellationToken)
        {
            var model = await _settingService.GetAsync(cancellationToken);
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(Setting setting, [FromHeader]CancellationToken cancellationToken)
        {

            var res = await _settingService.EditAsync(cancellationToken, setting);
            if (res==true)
            {
                TempData["Success"] = "تبریک . ویرایش تنظیمات با موفقیت انجام شد";
            }
            else
            {
                TempData["Error"] = "ویرایش ناموفق بود";
            }

            return RedirectToAction(nameof(Index));
        }
    }
}

Web/Areas/Admin/Controllers/StudentController.cs
using Microsoft.AspNetCore.Mvc;
using Services;
using Services.Enum.ServicesResult.Student;
using System.Threading;
using System.Threading.Tasks;



namespace Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Route("[area]/[controller]/[action]")]
    public class StudentController : Controller
    {
        private readonly IStudentService _studentService;

        public StudentController(IStudentService studentService)
        {
            _studentService = studentService;
        }
        public async Task<IActionResult> Index([FromHeader]CancellationToken cancellationToken)
        {
            var model = await _studentService.GetAllAsync(cancellationToken);
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(string studentId, [FromHeader] CancellationToken cancellationToken)
        {
            var res = await _studentService.DeleteAsync(studentId, cancellationToken);
            if (res == DeleteAsyncStatus.Ok)
            {
                TempData["War"] = "کتاب مورد نظر حذف شد";
                return RedirectToAction(nameof(Index));
            }
            else if (res == DeleteAsyncStatus.NonExists)
            {
                TempData["Error"] = "کتاب مورد نظر یافت نشد";
                return RedirectToAction(nameof(Index));
            }

            TempData["Error"] = "مشکلی در حذف کتاب به وجود آمد";
            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public async Task<IActionResult> Details(string id, [FromHeader]CancellationToken cancellationToken)
        {
            var model = await _studentService.FindByIdAsync(id, cancellationToken);
            var res = model.Data;
            if (res == null)
            {
                TempData["Error"] = "کتاب مورد نظر یافت نشد";
                return RedirectToAction(nameof(Index));
            }
            return View(res);
        }

     

    }
}

Web/Areas/Admin/Views/Shared/_Adminlayout.cshtml
<!DOCTYPE html>
<!--
This is a starter template page. Use this page to start your new project from
scratch. This page gets rid of all links and provides the needed markup only.
-->
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>صفحه شروع | کنترل پنل</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <!-- Bootstrap 3.3.7 -->
    <link rel="stylesheet" href="~/Adminfiles/dist/css/bootstrap-theme.css">
    <!-- Bootstrap rtl -->
    <link rel="stylesheet" href="~/css/bootstrap.min.css">
    <link rel="stylesheet" href="~/Adminfiles/dist/css/rtl.css">
    <!-- Favicon
    ============================================ -->
    <link rel="shortcut icon" type="image/x-icon" href="~/favicon.ico">
    <!--for Graphical checkBox And Radio-->
    <link href="~/Adminfiles/iCheck/all.css" rel="stylesheet" />

    <!-- Font Awesome -->
    <link rel="stylesheet" href="~/Adminfiles/bower_components/font-awesome/css/font-awesome.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="~/Adminfiles/bower_components/Ionicons/css/ionicons.min.css">

    <!-- Theme style -->
    <link rel="stylesheet" href="~/Adminfiles/dist/css/AdminLTE.css">
    <!-- AdminLTE Skins. We have chosen the skin-blue for this starter
          page. However, you can choose any other skin. Make sure you
          apply the skin class to the body tag so the changes take effect. -->
    <link rel="stylesheet" href="~/Adminfiles/dist/css/skins/skin-blue.min.css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    <!-- Google Font -->
    <link rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
    <link href="~/lib/jstree/themes/default/style.min.css" rel="stylesheet" />

    <link href="~/lib/toastr/toastr.min.css" rel="stylesheet" />
    <link href="~/css/mystyle.css" rel="stylesheet" />
</head>

<!--
BODY TAG OPTIONS:
=================
Apply one or more of the following classes to get the
desired effect
|---------------------------------------------------------|
| SKINS         | skin-blue                               |
|               | skin-black                              |
|               | skin-purple                             |
|               | skin-yellow                             |
|               | skin-red                                |
|               | skin-green                              |
|---------------------------------------------------------|
|LAYOUT OPTIONS | fixed                                   |
|               | layout-boxed                            |
|               | layout-top-nav                          |
|               | sidebar-collapse                        |
|               | sidebar-mini                            |
|---------------------------------------------------------|
-->
<body class="hold-transition skin-blue sidebar-mini">
    <div class="wrapper">


        <!-- Main Header -->
        <header class="main-header">
            <!-- Logo -->
            <a href="index2.html" class="logo">
                <!-- mini logo for sidebar mini 50x50 pixels -->
                <span class="logo-mini">پنل</span>
                <!-- logo for regular state and mobile devices -->
                <span class="logo-lg"><b>کنترل پنل مدیریت</b></span>
            </a>
            <!-- Header Navbar: style can be found in header.less -->
            <!--Start nav-->
            <partial name="_navPartial" />
            <!--End nav-->
        </header>
        <!--start right side column. contains the logo and sidebar -->
        <partial name="_asidePartial" />
        <!--End aside-->
        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            <!-- Content Header (Page header) -->
            <section class="content-header">
                <h4>
                    @ViewBag.ViewTitle
                </h4>
                <ol class="breadcrumb">
                    <li><a href="#"><i class="fa fa-dashboard"></i> خانه</a></li>
                    <li class="active">صفحه</li>
                </ol>
            </section>

            <!-- Main content -->
            <section class="content container-fluid">
                @RenderBody()
                <!--------------------------
                | Your Page Content Here |
                -------------------------->

            </section>
            <!-- /.content -->
        </div>
        <!-- /.content-wrapper -->
      
    </div>
    <!-- ./wrapper -->
    <!-- REQUIRED JS SCRIPTS -->
    <!-- jQuery 3 -->
    <script src="~/Adminfiles/bower_components/jquery/dist/jquery.min.js"></script>
    <!-- Bootstrap 3.3.7 -->
    <script src="~/Adminfiles/bower_components/bootstrap/dist/js/bootstrap.min.js"></script>
    <!-- AdminLTE App -->
    <script src="~/Adminfiles/dist/js/adminlte.min.js"></script>


    <!--Jquery For Graphical CheckBox And Radio-->
    <script src="~/Adminfiles/iCheck/icheck.min.js"></script>
    <script src="~/lib/toastr/toastr.min.js"></script>
    <script>
         $(function() {

             if ('@TempData["Error"]' != "") {
                toastr.error('@TempData["Error"]');
             }


             if ('@TempData["War"]' != "") {
                 toastr.warning('@TempData["War"]');
             }

             if ('@TempData["Info"]' != "") {
                 toastr.info('@TempData["Info"]');
             }

             if ('@TempData["Success"]' != "") {
                 toastr.success('@TempData["Success"]');
             }
        })
    </script>

    @RenderSection("PanelScripts", required: false)

    <!-- Optionally, you can add Slimscroll and FastClick plugins.
         Both of these plugins are recommended to enhance the
         user experience. -->
</body>
</html>

Web/Areas/Admin/Views/Shared/_asidePartial.cshtml
<aside class="main-sidebar">

    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">

        <!-- Sidebar user panel (optional) -->
        <div class="user-panel">
            <div class="pull-right image">
                <img src="~/Adminfiles/dist/img/user2-160x160.jpg" class="img-circle" alt="User Image">
            </div>
            <div class="pull-right info">
                <p>حامد حاجیلو</p>
                <!-- Status -->
                <a href="#"><i class="fa fa-circle text-success"></i> آنلاین</a>
            </div>
        </div>

        <!-- search form (Optional) -->
        <form action="#" method="get" class="sidebar-form">
            <div class="input-group">
                <input type="text" name="q" class="form-control" placeholder="جستجو">
                <span class="input-group-btn">
                    <button type="submit" name="search" id="search-btn" class="btn btn-flat">
                        <i class="fa fa-search"></i>
                    </button>
                </span>
            </div>
        </form>
        <!-- /.search form -->
        <!-- Sidebar Menu -->
        <ul class="sidebar-menu" data-widget="tree">
            <!-- Optionally, you can add icons to the links -->
            <li class="treeview active">
                <a href="#">
                    <i class="fa fa-assistive-listening-systems"></i> <span>مدیریت سیستم</span>
                    <span class="pull-left-container">
                        <i class="fa fa-angle-right pull-left"></i>
                    </span>
                </a>
                <ul class="treeview-menu">
                    <li class="treeview">
                        <a href="#">
                            <i class="fa fa-user"></i><span>مدیریت کاربران</span>
                            <span class="pull-left-container">
                                <i class="fa fa-angle-right pull-left"></i>
                            </span>
                        </a>
                        <ul class="treeview-menu">
                            <li><a asp-controller="Student" asp-action="Index">  <i class="ion ion-university"></i>دانشجو </a></li>
                            <li><a asp-controller="Teacher" asp-action="Index">  <i class="fa fa-university"></i>استاد </a></li>
                            <li><a asp-controller="Personel" asp-action="Index">  <i class="fa fa-university"></i>پرسنل </a></li>
                        </ul>
                    </li>
                    <li><a asp-controller="Books" asp-action="Index"><i class="fa fa-book"></i> مدیریت کتاب ها</a></li>
                </ul>
            </li>
            <li><a asp-controller="News" asp-action="Index"><i class="fa fa-newspaper-o"></i> <span>مدیریت اخبار</span></a></li>
            <li><a asp-controller="Setting" asp-action="Index"><i class="ion ion-settings"></i> <span>تنظیمات</span></a></li>
            
        </ul>
        <!-- /.sidebar-menu -->
    </section>
    <!-- /.sidebar -->
</aside>